from __future__ import annotations

from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol

from app.domain.enums import EntryDirection, HoldStatus, InstructionStatus, InstructionType, NormalBalance


class RepositoryTx(Protocol):
    def __enter__(self) -> "RepositoryTx": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...

    def upsert_account(self, account_id: str, customer_id: str, normal_balance: NormalBalance) -> None: ...
    def get_account(self, account_id: str) -> dict | None: ...
    def list_accounts(self) -> list[dict]: ...
    def list_accounts_by_customer(self, customer_id: str) -> list[dict]: ...
    def create_instruction(
        self,
        instruction_id: str,
        instruction_type: InstructionType,
        status: InstructionStatus,
        idempotency_key: str,
        request_hash: str,
        request_json: str,
    ) -> None: ...
    def get_instruction_by_idempotency_key(self, idempotency_key: str) -> dict | None: ...
    def get_instruction(self, instruction_id: str) -> dict | None: ...
    def update_instruction_result(
        self,
        instruction_id: str,
        status: InstructionStatus,
        response_json: str,
    ) -> None: ...
    def create_transfer(self, transfer_id: str, instruction_id: str, phase: str) -> None: ...
    def create_transfer_entry(
        self,
        entry_id: str,
        transfer_id: str,
        account_id: str,
        direction: EntryDirection,
        amount_cents: int,
    ) -> None: ...
    def list_transfer_entries(self) -> list[dict]: ...
    def list_transfer_entries_for_account(self, account_id: str) -> list[dict]: ...
    def create_hold(
        self,
        auth_instruction_id: str,
        hold_account_id: str,
        checking_account_id: str,
        original_amount_cents: int,
        remaining_amount_cents: int,
        expires_at: datetime,
        status: HoldStatus,
    ) -> None: ...
    def get_hold(self, auth_instruction_id: str) -> dict | None: ...
    def list_holds(self) -> list[dict]: ...
    def update_hold(self, auth_instruction_id: str, remaining_amount_cents: int, status: HoldStatus) -> None: ...
    def list_expired_holds(self, now: datetime) -> list[dict]: ...
    def append_event(self, event_id: str, event_type: str, payload_json: str) -> None: ...
    def list_events(self) -> list[dict]: ...


class Repository(Protocol):
    def transaction(self) -> AbstractContextManager[RepositoryTx]: ...
